# Generated by Django 4.1.4 on 2022-12-07 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="added_by",
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
